version: '3.8'

services:
  imap2rss:
    build: .
    container_name: imap2rss
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8888"  # RSS server port (localhost only)
      - "127.0.0.1:9999:9999"  # Configuration GUI port (localhost only)
    env_file:
      - .env
    
    volumes:
      - ./data:/app/data                  # Persist RSS feed data
      - ./.env:/app/.env                  # Persist configuration file
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data: